const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs');const path=require('path');const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});try{const results=[];
for(const lang of ['en','zh']){const page=await browser.newPage({viewport:{width:1360,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.COMPASS_URL||'http://127.0.0.1:35496')+'/?lang='+lang);await page.locator('.ant-pagination-item-2').click();await page.waitForFunction(()=>window.queries.at(-1)?.page===2);await page.locator('a[href="/analyze/s31"]').waitFor();
const before=await page.evaluate(()=>({query:window.queries.at(-1),cards:document.querySelectorAll('a[href^="/analyze/"]').length}));assert.equal(before.cards,30);
const input=page.getByPlaceholder(lang==='en'?'Search repository':'搜索仓库');await input.fill('needle');await input.press('Enter');await page.waitForFunction(()=>window.queries.at(-1)?.keyword==='needle');await page.locator('.ant-pagination-item-active').waitFor();
const afterSearch=await page.evaluate(()=>({query:window.queries.at(-1),cards:document.querySelectorAll('a[href^="/analyze/"]').length,displayedPage:document.querySelector('.ant-pagination-item-active')?.textContent,body:document.body.innerText,queries:[...window.queries]}));
assert.equal(afterSearch.query.page,2);assert.equal(afterSearch.cards,0);assert.equal(afterSearch.displayedPage,'1');
await page.screenshot({path:path.join(__dirname,`baseline-${lang}-search.png`),fullPage:true});
await page.locator('.ant-pagination-item-1').click();await page.waitForTimeout(100);const recovery=await page.evaluate(()=>({query:window.queries.at(-1),cards:document.querySelectorAll('a[href^="/analyze/"]').length,queries:[...window.queries]}));
assert.equal(recovery.query.page,2);assert.equal(recovery.cards,0);assert.equal(recovery.queries.length,afterSearch.queries.length);assert.equal(errors.length,0);results.push({lang,before,afterSearch,recovery,errors});await page.close();}
const report={upstreamBase:'d709b1898549c5ab4091302a4c26f45bbe198c66',observedAt:new Date().toISOString(),browserVersion:browser.version(),boundary:'Actual collection components and Antd pagination; real generated GraphQL hook and React Query; synthetic GraphQL client transport with standard unclamped page slicing. Does not claim live backend behavior.',results};fs.writeFileSync(path.join(__dirname,'baseline-browser.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
